### ISSUE TITLE
Initial Value still shown in Show select Items

### ISSUE THREAD

**Issue by chhily** [esentis/multiple_search_selection#18]
## Current Behavior

A clear and concise description of the behavior.

## Expected behavior/code

A clear and concise description of what you expected to happen (or code).

### Environment

- Operating System
- `flutter doctor -v`

### Possible Solution

`Only if you have suggestions on a fix for the bug`

### Additional context/Screenshots

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by esentis** [comment]
Hello there, thanks for using my library and for filling this issue. However, I don't know if I understand the issue. Can you please provide an example ?

**Comment by chhily** [comment]
Hey, thanks for replied back

https://user-images.githubusercontent.com/106373333/209596384-acb371c1-ceaf-4f54-9df3-5de46f339096.mp4

As you see in vid above, It shown Vegetable and Fruit as Initial value but it is still show you to select in Show Item, Dialog.

Once again great packet!

**Comment by esentis** [comment]
Ok I think I've got it. Are you sure the `items` parameter doesn't have the same items as `initialPickedItems` ? 
The package doesn't automatically exclude the items of `initialPickedItems` from the `items`. 
If this is the case, you can try filtering out the `items` to exclude the `initialPickedItems` and you are good to go. Some people may want to have dublicates in the list, this is the reason I'm not the one doing the filtering. 

If the issue is still not resolved, please provide the code to check out what `initialPickedItems` & `items` you are passing to the `widget`.

**Comment by chhily** [comment]
Got it, what seem to be problem is I initialed it as ID not an actual Item in value field. 
Thanks for help!
